### ISSUE TITLE
Add external links

### ISSUE THREAD

**Issue by GLD5000** [GLD5000/LDW-GLD#10]

**Comment by dingaaling** [comment]
- Twitter: https://twitter.com/londondataweek
- Eventbrite: https://www.eventbrite.com/o/london-data-week-64463396023
- Github: remove link/logo

**Comment by dingaaling** [comment]
Logos
- ![image 7](https://user-images.githubusercontent.com/5104098/232220809-169ab089-c136-4232-b4a5-15930144002f.png)
- ![image 11](https://user-images.githubusercontent.com/5104098/232220820-705d9db1-79b6-489e-98de-8d977258c0cf.png)
