### ISSUE TITLE
Add about content

### ISSUE THREAD

**Issue by GLD5000** [GLD5000/LDW-GLD#14]

**Comment by dingaaling** [comment]
- About copy:
```
Data is part of our everyday lives as Londoners, from choosing the best Tube route to finding your next pair of trainers.
Join us at London Data Week for a 
citywide festival about data to 
learn, discuss, explore, and create 
how to use data to shape our city for the better.
Explore our schedule to discover workshops, comedy events, cycling challenges and more!
```
- About design: https://www.figma.com/file/xCxR58NgQpJYsjbbNlIRKB/LDW-Website?node-id=70-41&t=ZMwxgajGPHRKR1yA-0

**Comment by GLD5000** [comment]
Need to reorder:
"to  learn, discuss, explore, and create how to use data to shape our city"
to:
"to learn, create, discuss, and explore how to use data to shape our city"
