### ISSUE TITLE
Change website font to Poppins

### ISSUE THREAD

**Issue by dingaaling** [GLD5000/LDW-GLD#25]
Currently the header, body, event schedule, and other text do not seem to be Poppins

**Comment by GLD5000** [comment]
Which browser / OS please?

Below is what I am seeing on my end:

![image](https://user-images.githubusercontent.com/33987109/232309936-8c0002e6-f448-48e2-87b8-768cbc213ebb.png)
![image](https://user-images.githubusercontent.com/33987109/232309964-1f0e48ce-1aa1-439f-a0b3-1b7eb82b8965.png)
![image](https://user-images.githubusercontent.com/33987109/232310000-20f4c30a-06f9-48c9-ac81-796fb3a5790a.png)
![image](https://user-images.githubusercontent.com/33987109/232310018-7adebcf3-d7de-485e-b008-89713d15895e.png)

**Comment by dingaaling** [comment]
Tested on Arc and Chrome - the font looks like Arial to me (not Poppins), see screenshot below for comparison (left: Poppins in Figma, right: Arial on website). Could it be that Arial you have is overriding the Poppins somehow?

The screenshots you shared also look like Arial to me.

<img width="1771" alt="Screenshot 2023-04-16 at 14 48 06" src="https://user-images.githubusercontent.com/5104098/232315809-d7f84d07-f0f7-4ab3-a354-01df0a0cf962.png">
